import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import MenuBar from '@/components/MenuBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',

  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto h-screen w-[600px]">
          <header className="fixed top-0 z-50">
            <Header />
          </header>

          <main className="h-screen">{children}</main>

          <footer className="fixed bottom-0 z-50">
            <MenuBar />
          </footer>
        </div>
      </body>
    </html>
  );
}
